import '../../deepyr.dart';

mixin AllComponentStylings
    implements
        AccordionStyling,
        AlertStyling,
        AvatarStyling,
        BadgeStyling,
        ButtonStyling,
        BreadcrumbsStyling,
        CardStyling,
        CheckboxStyling,
        CollapseStyling,
        DiffStyling,
        DividerStyling,
        DrawerStyling,
        DropdownStyling,
        DropdownContentStyling,
        FieldsetStyling,
        FileInputStyling,
        FooterStyling,
        FormLabelStyling,
        HeroStyling,
        IconStyling,
        IndicatorStyling,
        IndicatorItemStyling,
        InputStyling,
        JoinStyling,
        KbdStyling,
        LabelStyling,
        LegendStyling,
        LinkStyling,
        LoadingStyling,
        MenuStyling,
        MenuItemStyling,
        ModalStyling,
        NavbarStyling,
        ProgressStyling,
        RadioStyling,
        RangeStyling,
        SelectStyling,
        SkeletonStyling,
        SwapStyling,
        TabsStyling,
        TabStyling,
        TextareaStyling,
        ThemeControllerStyling,
        ToggleStyling,
        TooltipStyling,
        ValidatorHintStyling {
  // Empty mixin - only Interface
}
