import '../components/button/button_style.dart';

mixin AllComponentStylings implements ButtonStyling {
  // Empty mixin - nur Interface-Implementierung
}

/* Build-Script für automatische Generation

// tool/generate_stylings.dart
import 'dart:io';
import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:path/path.dart' as path;

void main() async {
  print('Generating AllComponentStylings mixin...');

  // Finde alle *Styling interfaces in components/
  final stylingInterfaces = await findAllStylingInterfaces();

  // Generiere Mixin
  final mixinCode = generateMixin(stylingInterfaces);

  // Schreibe in generated file
  final outputFile = File('lib/src/base/generated_stylings.dart');
  await outputFile.writeAsString(mixinCode);

  print('Generated mixin with ${stylingInterfaces.length} interfaces');
}

Future<List<String>> findAllStylingInterfaces() async {
  final interfaces = <String>[];
  final componentsDir = Directory('lib/src/components');

  await for (final entity in componentsDir.list(recursive: true)) {
    if (entity is File && entity.path.endsWith('_style.dart')) {
      final content = await entity.readAsString();

      // Regex um "abstract class XxxStyling" zu finden
      final regex = RegExp(r'abstract class (\w+Styling)');
      final matches = regex.allMatches(content);

      for (final match in matches) {
        interfaces.add(match.group(1)!);
      }
    }
  }

  return interfaces..sort();
}

String generateMixin(List<String> interfaces) {
  return '''
// GENERATED CODE - DO NOT EDIT
// Generated by: dart run tool/generate_stylings.dart
// Generated at: ${DateTime.now().toIso8601String()}

${interfaces.map((i) => "import '../components/${_getComponentPath(i)}';").join('\n')}

/// Auto-generated mixin that implements all ComponentStyling interfaces.
/// This allows CommonStyle utilities to be used with any component.
mixin AllComponentStylings implements
${interfaces.map((i) => '    $i').join(',\n')} {
  // Empty mixin - provides interface implementations only
}
''';
}

String _getComponentPath(String interfaceName) {
  // ButtonStyling -> button/button_style.dart
  final componentName = interfaceName
      .replaceAll('Styling', '')
      .toLowerCase();
  return '$componentName/${componentName}_style.dart';
}
*/
